---
- hosts: all
  sudo: true
  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress

  tasks:
    - name: install sysstat
      apt: name=sysstat state=present
    - name: install htop
      apt: name=htop state=present
